# Generated by Django 6.0 on 2025-12-29 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifypreference',
            name='user',
        ),
        migrations.AlterField(
            model_name='spotifypreference',
            name='spotify_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='viewset_spotify.spotifyuser', to_field='spotify_id'),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
